-- MySQL Script generated by MySQL Workbench
-- Wed Jan  3 16:05:26 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema guild_build
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema guild_build
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `guild_build` DEFAULT CHARACTER SET utf8 ;
USE `guild_build` ;

-- -----------------------------------------------------
-- Table `guild_build`.`igra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `guild_build`.`igra` (
  `sifIgre` INT(11) NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`sifIgre`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `guild_build`.`ceh`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `guild_build`.`ceh` (
  `sifCeh` INT(11) NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(20) NOT NULL,
  `sifIgre` INT(11) NOT NULL,
  `opis` VARCHAR(2500) NULL DEFAULT NULL,
  PRIMARY KEY (`sifCeh`),
  INDEX `igra_idx` (`sifIgre` ASC),
  CONSTRAINT `igra`
    FOREIGN KEY (`sifIgre`)
    REFERENCES `guild_build`.`igra` (`sifIgre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `guild_build`.`dogadaj`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `guild_build`.`dogadaj` (
  `sifDog` INT(11) NOT NULL AUTO_INCREMENT,
  `nazivDog` VARCHAR(100) NOT NULL,
  `sifCeh` INT(11) NOT NULL,
  `ispunjen` BIT(1) NULL DEFAULT b'0',
  `vidljiv` BIT(1) NULL DEFAULT b'0',
  PRIMARY KEY (`sifDog`),
  INDEX `ceh_idx` (`sifCeh` ASC),
  CONSTRAINT `ceh`
    FOREIGN KEY (`sifCeh`)
    REFERENCES `guild_build`.`ceh` (`sifCeh`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `guild_build`.`cilj`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `guild_build`.`cilj` (
  `sifCilja` INT(11) NOT NULL AUTO_INCREMENT,
  `nazivCilja` VARCHAR(50) NOT NULL,
  `sifDog` INT(11) NOT NULL,
  `ispunjen` BIT(1) NULL DEFAULT b'0',
  PRIMARY KEY (`sifCilja`),
  INDEX `dogadaj_idx` (`sifDog` ASC),
  CONSTRAINT `dogadaj`
    FOREIGN KEY (`sifDog`)
    REFERENCES `guild_build`.`dogadaj` (`sifDog`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `guild_build`.`klasa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `guild_build`.`klasa` (
  `sifKlase` INT(11) NOT NULL AUTO_INCREMENT,
  `naziv` VARCHAR(20) NOT NULL,
  `sifIgre` INT(11) NOT NULL,
  PRIMARY KEY (`sifKlase`),
  INDEX `igraa_idx` (`sifIgre` ASC),
  CONSTRAINT `igraa`
    FOREIGN KEY (`sifIgre`)
    REFERENCES `guild_build`.`igra` (`sifIgre`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `guild_build`.`korisnik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `guild_build`.`korisnik` (
  `nadimak` VARCHAR(20) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `lozinka` VARCHAR(16) NOT NULL,
  `statusR` BIT(1) NULL DEFAULT b'0',
  `rang` VARCHAR(11) NULL DEFAULT NULL,
  `sifCeh` INT(11) NULL DEFAULT '0',
  `statusP` BIT(1) NULL DEFAULT b'0',
  `opis` VARCHAR(2500) NULL DEFAULT NULL,
  `isAdmin` BIT(1) NULL DEFAULT b'0',
  PRIMARY KEY (`nadimak`, `email`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `guild_build`.`lik`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `guild_build`.`lik` (
  `nadimak` VARCHAR(20) NOT NULL,
  `level` INT(11) NULL DEFAULT '1',
  `sifKlase` INT(11) NOT NULL,
  `craftingSkills` VARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`nadimak`, `sifKlase`),
  INDEX `klasaa_idx` (`sifKlase` ASC),
  CONSTRAINT `klasaa`
    FOREIGN KEY (`sifKlase`)
    REFERENCES `guild_build`.`klasa` (`sifKlase`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `vlasnik`
    FOREIGN KEY (`nadimak`)
    REFERENCES `guild_build`.`korisnik` (`nadimak`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `guild_build`.`obrazac`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `guild_build`.`obrazac` (
  `sifCeha` INT(11) NOT NULL,
  `nadimak` VARCHAR(20) NOT NULL,
  `poruka` VARCHAR(1000) NULL DEFAULT NULL,
  PRIMARY KEY (`sifCeha`, `nadimak`),
  INDEX `vlasnikO_idx` (`nadimak` ASC),
  CONSTRAINT `ceh1`
    FOREIGN KEY (`sifCeha`)
    REFERENCES `guild_build`.`ceh` (`sifCeh`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `vlasnikO`
    FOREIGN KEY (`nadimak`)
    REFERENCES `guild_build`.`korisnik` (`nadimak`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `guild_build`.`podcilj`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `guild_build`.`podcilj` (
  `sifPodcilja` INT(11) NOT NULL AUTO_INCREMENT,
  `nazivCilja` VARCHAR(50) CHARACTER SET 'utf8' COLLATE 'utf8_general_mysql500_ci' NOT NULL,
  `sifCilja` INT(11) NOT NULL,
  `ispunjen` BIT(1) NULL DEFAULT b'0',
  PRIMARY KEY (`sifPodcilja`),
  INDEX `cilj_idx` (`sifCilja` ASC),
  CONSTRAINT `cilj`
    FOREIGN KEY (`sifCilja`)
    REFERENCES `guild_build`.`cilj` (`sifCilja`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_mysql500_ci;

CREATE USER 'java' IDENTIFIED BY 'password';

GRANT ALL ON `guild_build`.* TO 'java';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
